### ISSUE TITLE
Can't find some properties .. 

### ISSUE THREAD

**Issue by ZalyalovIldar** [paulrolfe/PARTagPicker#5]
First of all, thanks for this amazing tool!
There are  thing that I can't find. Firstly, i can't call textField in my controller for edit placeholder or another properties. Secondly, i can't find some property to stop removing tags by double tapping. And can I change only first tag border,background and text color? 
I found textfield in the library, and change placeholder, but I thing there should be properly way to do it. 
Pleas, help with it.

**Comment by paulrolfe** [comment]
Hello! I'm glad it's helping you. Unfortunately I don't have those properties created or exposed. I do appreciate the idea and think they'd make good additions. I could add them in the next day or two.

You are welcome to fork and submit a pull request if you want. Otherwise I'll be adding it by the end of the weekend.

Thanks!

**Comment by ZalyalovIldar** [comment]
Ok, I'll be waiting, thanks.

**Comment by paulrolfe** [comment]
Got it done now. Let me know if that's in line with what you were thinking, @ZalyalovIldar.  See version 1.1.0 ( #6 )
